'use client'
import { PageHero, CTA } from './FoundryShell'
import RuleLedger from './RuleLedger'
export default function GovernanceContent(){return <>
<PageHero eyebrow="Governance · Authority you define" title={<>Give responsibility.<br/><em>Keep authority.</em></>} lead="A company needs to decide what its AI may do, what needs approval, and how to review the result. These are the principles behind our approach to delegated work." actions={<a className="btn btn-solid" href="#demonstration">Try the illustration →</a>}/>
<section className="section"><div className="wrap company-principles technology-principles"><article><h2 className="serif">Scope the work.</h2><p>A responsibility needs explicit limits: the action, the information it may use, and the circumstances that require a person’s decision.</p></article><article><h2 className="serif">Make decisions traceable.</h2><p>The record should connect a decision to the instruction and authority behind it, with a clear outcome a business owner can understand.</p></article><article><h2 className="serif">Withdraw permission.</h2><p>Revocation stops future actions from using that grant. It does not unsend a message, reverse a completed payment, or erase the record. Work already underway needs its own handling.</p></article><article><h2 className="serif">Verify the workflow.</h2><p>The connected service, permissions, approval requirements, and failure handling need to be checked for each company. A simulation does not establish production coverage.</p></article></div></section>
<section className="section demo-section" id="demonstration"><div className="wrap"><p className="eyebrow">Interactive illustration · No live business actions</p><h2 className="serif" style={{fontSize:'clamp(32px,4vw,54px)',marginBlock:'20px'}}>Try a grant. Review a decision. Revoke it.</h2><p className="demo-lead">This simplified simulation runs only in your browser and resets on reload. It illustrates granting a responsibility, checking an example request, and preserving history after revocation. It does not connect to a company account or execute real work.</p><RuleLedger/><p className="demo-foot">The examples are illustrative rules, not a demonstration of a live permission service. Discuss your actual workflow and its limits with the team.</p></div></section>
<CTA title={<>Start with one <em>responsibility.</em></>} lead="Tell us where your team needs help and what decisions must remain with you." actions={<><a className="btn btn-solid" href="https://hiresabina.ai">Meet Sabina →</a><a className="btn btn-ghost" href="mailto:foundry@dominusfoundry.com">Contact the team →</a></>}/>
</>}
