'use client'
import { Medallion, Icon } from './Marks'
import { CTA } from './FoundryShell'
export default function HomeContent() {
 return <>
  <section className="hero on-dark company-hero" id="top"><div className="wrap company-hero-grid">
   <div><p className="eyebrow">Dominus Foundry · The intelligence company</p>
    <h1 className="hero-title">Hired AI.<br/>Built around <em>your business.</em></h1>
    <p className="hero-lead">We build Sabina: a dedicated AI shaped around a company’s knowledge, responsibilities, and the authority its people give her.</p>
    <div className="hero-actions"><a className="btn btn-solid" href="https://hiresabina.ai">Meet Sabina {Icon.arr}</a><a className="btn btn-ghost" href="https://markflord.com/pitch">For investors {Icon.arr}</a></div>
   </div><div className="company-seal"><Medallion scheme="ondark"/><p className="serif">Fide et Familia</p><span>Built &amp; held by the Lord family</span></div>
  </div></section>
  <section className="section"><div className="wrap thesis-grid"><div><p className="eyebrow">What we are building</p><h2 className="thesis-line">Intelligence with a place<br/><em>in the company.</em></h2></div><div className="thesis-aside"><p>A business has its own way of working: relationships, commitments, records, and decisions that carry consequences. Its AI should work within that context.</p><p>Sabina is the focus of Dominus Foundry. We bring the company knowledge, delegated work, and oversight together so a team can start with a defined responsibility and expand deliberately.</p><a className="section-more" href="/sabina">Meet the company AI →</a></div></div></section>
  <section className="section darkband"><div className="wrap"><p className="eyebrow">Authority belongs to the business</p><h2>Useful work begins<br/>with <em>clear boundaries.</em></h2><p className="darkband-lead">What may she do? What needs your approval? What happened? These are the questions that guide how we build.</p><div className="company-principles"><article><h3>Give her a responsibility.</h3><p>Define the work, the information she can use, and the limits that matter to your team.</p></article><article><h3>Keep the work visible.</h3><p>Make decisions and outcomes understandable to the people responsible for them.</p></article><article><h3>Change the authority.</h3><p>Withdraw permission for future work when circumstances change. Completed actions keep their history.</p></article></div><a className="section-more on-dark-more" href="/governance">Explore the governance approach →</a></div></section>
  <section className="section"><div className="wrap company-paths"><article><p className="eyebrow">The people behind her</p><h2 className="serif">Mark &amp; Bri Lord.</h2><p>We came to this work through running businesses. The missed handoffs, scattered information, and daily follow-through were familiar long before we started building Sabina.</p><a className="section-more" href="/company">Meet the founders →</a></article><article><p className="eyebrow">The first operating context</p><h2 className="serif">Grounded in real work.</h2><p>Forge is our contractor vertical and the first business context for Sabina. It informs the work; the company’s focus is the intelligence that serves the team.</p><a className="section-more" href="https://buildwithforge.app">Explore Forge for contractors →</a></article></div></section>
  <CTA eyebrow="Customers · Investors · Partners" title={<>Let’s talk about <em>your company.</em></>} lead="Explore Sabina for your business, or contact Mark and Bri about working together." actions={<><a className="btn btn-solid" href="https://hiresabina.ai">Meet Sabina {Icon.arr}</a><a className="btn btn-ghost" href="mailto:foundry@dominusfoundry.com">Contact the team {Icon.arr}</a></>}/>
 </>
}
