'use client'
import { PageHero, CTA } from './FoundryShell'
/* RETOOL 2026-10-07 (HANDOFF §5.3, §2.1): the generic middle is replaced by the
   four-layer architecture, in the existing principles grid. Each card states the
   reusable Foundry asset and the company-specific state separately. ⛔ Do not
   describe a new base training run per customer; ⛔ do not publish a
   database-level boundary claim until it is verified against the settled
   technical source (see the retool report). */
const layers = [
 ['Trained core', 'Foundry trains and operates the core model that supplies Sabina’s reasoning and behavior.', 'Reusable: custom-trained weights, training and evaluation methods, serving software.', 'Company-specific: any additional adaptation explicitly included in that deployment. A new base training run is not implied.'],
 ['Company identity and memory', 'Sabina starts with the relevant context of the company and its industry.', 'Reusable: proprietary memory, context assembly and onboarding machinery, and industry starting points.', 'Company-specific: identity, systems, people, records, relationships and private knowledge.'],
 ['Company teaching and authority', 'The company teaches how work should be handled and defines what Sabina may do.', 'Reusable: the proprietary teaching and customization process and the authority machinery.', 'Company-specific: operating instructions, responsibilities, grants, conditions, approvals and revocation.'],
 ['Accumulating company intelligence', 'Authorized email, employee interactions, decisions and outcomes add useful knowledge for later work and analysis.', 'Reusable: knowledge acquisition, memory maintenance, retrieval and synthesis mechanisms.', 'Company-specific: operational history, corrections, relationships, precedents and growing understanding.'],
]
export default function TechnologyContent(){return <>
<PageHero eyebrow="Technology · The system behind Sabina" title={<>One trained core.<br/><em>AI shaped around each company.</em></>} lead="Sabina runs on a core model trained and operated by Foundry. Our proprietary memory and teaching systems shape that foundation around your company, while your permissions define what she may do." actions={<><a className="btn btn-solid" href="https://hiresabina.ai/evaluate">See Sabina work</a><a className="btn btn-ghost" href="/governance">Explore governance →</a></>}/>
<section className="section"><div className="wrap"><p className="eyebrow">Four layers · reusable platform and private company state</p><div className="company-principles technology-principles">{layers.map(([title,body,reusable,company])=><article key={title}><h2 className="serif">{title}</h2><p>{body}</p><p>{reusable}</p><p>{company}</p></article>)}</div><p style={{marginTop:'32px',maxWidth:'62ch',lineHeight:1.75}}>The shared model and common software support distinct company systems. Company teaching and memory personalize the complete system, while the Foundry-trained core remains reusable. Your company’s knowledge, memory, operating instructions, and permissions remain specific to your company. Access follows the sources and authority you approve.</p></div></section>
<section className="section darkband"><div className="wrap"><p className="eyebrow">Operated by Foundry</p><h2>We run the system.<br/><em>You decide the work.</em></h2><p className="darkband-lead">Foundry operates the model and the systems around it. Reusable provisioning, integrations, evaluations, and support processes let us deploy the same platform around the needs of different companies. You do not need to buy AI hardware for the office or build an AI department. The work a company can delegate still depends on its connected systems, permissions, and the workflows agreed for that company; the introduction film and governance simulation explain the approach and are not proof that every integration is available.</p></div></section>
<section className="section"><div className="wrap company-paths"><article><p className="eyebrow">Research &amp; development</p><h2 className="serif">Intellectual property.</h2><p>Patent pending. U.S. non-provisional application 19/791,511 was filed on 30 August 2026, following 19 provisional applications filed March–August 2026. These are filings, not granted patents, and a filing does not mean a product is available. For the delivery and scale plan, read the <a href="/pitch">investor case</a>.</p></article><article><p className="eyebrow">The platform beneath</p><h2 className="serif">Forge and DominusOS.</h2><p>Forge supplies operating records and specialist tools beneath and alongside Sabina; some Forge tools are sold on their own. DominusOS supplies the authority and execution-control architecture behind what Sabina is permitted to do. Forge tools are not automatically part of every Sabina deployment.</p><a className="section-more" href="https://buildwithforge.app">Explore Forge →</a></article></div></section>
<CTA title={<>Bring us a <em>real workflow.</em></>} lead="Tell us what your team needs help with. We can discuss fit, boundaries, and what would need to be demonstrated." actions={<><a className="btn btn-solid" href="mailto:foundry@dominusfoundry.com">Contact the team →</a><a className="btn btn-ghost" href="/governance">Authority and governance →</a></>}/>
</>}
