'use client'
import { PageHero, CTA } from './FoundryShell'
const principles = [
 ['Company context', 'The company’s knowledge, working relationships, and procedures give its AI a useful starting point. Access and scope should be agreed before a workflow is connected.'],
 ['Delegated responsibility', 'A task needs a purpose and a boundary. Which actions are permitted, which need approval, and when should a person take over? Those decisions belong to the business.'],
 ['An understandable record', 'People need to see what was requested, what was decided, and what happened. A fluent answer alone does not establish that work was completed.'],
 ['Learning with oversight', 'Corrections should improve future work while keeping business rules under human authority. A change in behavior needs to be distinguishable from a change in permission.'],
]
export default function TechnologyContent(){return <>
<PageHero eyebrow="Technology · Company intelligence" title={<>Built for the context<br/>of <em>one company.</em></>} lead="Our work centers on Sabina: connecting company knowledge, delegated responsibilities, and human oversight in a dedicated AI system." actions={<><a className="btn btn-solid" href="/sabina">Meet Sabina →</a><a className="btn btn-ghost" href="/governance">Explore governance →</a></>}/>
<section className="section"><div className="wrap"><p className="eyebrow">Our design approach</p><div className="company-principles technology-principles">{principles.map(([title,body])=><article key={title}><h2 className="serif">{title}</h2><p>{body}</p></article>)}</div></div></section>
<section className="section darkband"><div className="wrap"><p className="eyebrow">From a demonstration to your business</p><h2>Start with a workflow.<br/><em>Verify it together.</em></h2><p className="darkband-lead">The work a company can delegate depends on its connected systems, permissions, and the workflows qualified for that company. We discuss those specifics before making a commitment. The introduction film and governance simulation explain the approach; they are not proof that every integration is available.</p></div></section>
<section className="section"><div className="wrap company-paths"><article><p className="eyebrow">Research &amp; development</p><h2 className="serif">Intellectual property.</h2><p>Our research spans company intelligence, governance, and operational software. Patent applications describe specific inventions; they do not establish product availability or granted patent rights. Contact us for current filing information relevant to a partnership or investment discussion.</p></article><article><p className="eyebrow">Applied experience</p><h2 className="serif">Built close to the work.</h2><p>Forge provides a contractor operating context for this work. Product-specific tools and spatial capture belong with Forge, rather than defining the company’s whole technology story.</p><a className="section-more" href="https://buildwithforge.app">Explore the contractor vertical →</a></article></div></section>
<CTA title={<>Bring us a <em>real workflow.</em></>} lead="Tell us what your team needs help with. We can discuss fit, boundaries, and what would need to be demonstrated." actions={<a className="btn btn-solid" href="mailto:foundry@dominusfoundry.com">Contact the team →</a>}/>
</>}
