'use client'
import { PageHero, CTA } from './FoundryShell'
/* RETOOL 2026-10-07 (HANDOFF §5.3, §2.1): the generic middle is replaced by the
   four-layer architecture, in the existing principles grid (one body paragraph
   per card, as before). Each body names the reusable asset and the company state. ⛔ Do not
   describe a new base training run per customer; ⛔ do not publish a
   database-level boundary claim until it is verified against the settled
   technical source (see the retool report). */
const layers = [
 ['Trained core', 'Foundry trains and operates the core model behind Sabina’s reasoning. The weights, evaluation methods and serving software are reused across companies; a new base training run per company is not implied.'],
 ['Company identity and memory', 'Sabina starts with the context of the company and its industry. Foundry’s memory and onboarding machinery are reusable; the company’s identity, systems, people, records and private knowledge are its own.'],
 ['Company teaching and authority', 'The company teaches how work should be handled and defines what Sabina may do. The teaching process and authority machinery are reusable; instructions, grants, approvals and revocation belong to the company.'],
 ['Accumulating company intelligence', 'Authorized email, interactions, decisions and outcomes add knowledge for later work. Acquisition, retrieval and synthesis are reusable; the history, corrections and understanding stay with the company.'],
]
export default function TechnologyContent(){return <>
<PageHero eyebrow="Technology · The system behind Sabina" title={<>One trained core.<br/><em>AI shaped around each company.</em></>} lead="Sabina runs on a core model trained and operated by Foundry. Our proprietary memory and teaching systems shape that foundation around your company, while your permissions define what she may do." actions={<><a className="btn btn-solid" href="https://hiresabina.ai/evaluate">See Sabina work</a><a className="btn btn-ghost" href="/governance">Explore governance →</a></>}/>
<section className="section"><div className="wrap"><p className="eyebrow">Four layers · reusable platform and private company state</p><div className="company-principles technology-principles">{layers.map(([title,body])=><article key={title}><h2 className="serif">{title}</h2><p>{body}</p></article>)}</div></div></section>
<section className="section darkband"><div className="wrap"><p className="eyebrow">Operated by Foundry</p><h2>We run the system.<br/><em>You decide the work.</em></h2><p className="darkband-lead">Foundry operates the model and the systems around it, reusing provisioning, integrations, evaluations and support across companies, so you do not buy AI hardware or build an AI department. Your company’s knowledge, memory, instructions and permissions stay specific to your company, and access follows the sources and authority you approve. What a company can delegate still depends on its connected systems and the workflows agreed for it; the film and governance simulation explain the approach and are not proof that every integration is available.</p></div></section>
<section className="section"><div className="wrap company-paths"><article><p className="eyebrow">Research &amp; development</p><h2 className="serif">Intellectual property.</h2><p>Patent pending. Two U.S. non-provisional applications are on file: 19/791,511, filed 30 August 2026, and 19/817,646, a continuation-in-part filed 23 September 2026 covering governed organizational commitment reconciliation, constraint-aware work execution and evidence-verified fulfillment. They follow 19 provisional applications filed March–August 2026. These are filings, not granted patents, and a filing does not mean a product is available. For the delivery and scale plan, read the <a href="/pitch">investor case</a>.</p></article><article><p className="eyebrow">The platform beneath</p><h2 className="serif">Forge and DominusOS.</h2><p>Forge supplies operating records and specialist tools beneath and alongside Sabina; some Forge tools are sold on their own. DominusOS supplies the authority and execution-control architecture behind what Sabina is permitted to do. Forge tools are not automatically part of every Sabina deployment.</p><a className="section-more" href="https://buildwithforge.app">Explore Forge →</a></article></div></section>
<CTA title={<>Bring us a <em>real workflow.</em></>} lead="Tell us what your team needs help with. We can discuss fit, boundaries, and what would need to be demonstrated." actions={<a className="btn btn-solid" href="mailto:foundry@dominusfoundry.com">Contact the team →</a>}/>
</>}
