import Link from "next/link";
import Button from "../../components/Button";

export const metadata = {
  title: "DominusOS | Human-Governed AI Hypervisor | Dominus Foundry™",
  description:
    "DominusOS is a human-governed AI hypervisor — a mandatory control layer beneath AI execution that enforces structural authority, federated multi-kernel governance, and deterministic accountability.",
};

const guarantees = [
  {
    title: "Bounded Authority",
    body: "No process can exceed approved scope. Boundaries are enforced by capability envelopes, not configuration. Every process runs inside an explicit envelope — scoped, time-limited, and revocable — defined by a named human steward. Authority is structural, not behavioral.",
  },
  {
    title: "Attributable Action",
    body: "Every action traces to human authorization through an unbroken chain of attribution. Every record carries source, timestamp, evidence, and provenance. An auditor can reconstruct the full path from any outcome to the authority that sanctioned it.",
  },
  {
    title: "Governed Intelligence",
    body: "The system improves over time — but improvement requires human consent. Every proposed change is evidence-cited, reviewable, reversible, and gated by explicit authority. A cryptographically sealed constitutional canon ensures that governance rules cannot be altered by any automated process. Intelligence evolves inside governance, not outside it.",
  },
];

const authorityLayers = [
  {
    title: "Mandate",
    body: "Mandate defines intent and non-negotiable boundaries set by leadership, policy, or regulation. In DominusOS, these are immutable limits — enforced by constitutional canon — that AI processes cannot cross regardless of context.",
    highlight: false,
  },
  {
    title: "Operational Oversight",
    body: "Operational Oversight interprets that mandate in real time, authorizing scopes, approving behaviors, and issuing overrides when necessary. The syscall gate enforces this at the system level for every write, deploy, and financial action. Capability tokens are issued, bounded, and revocable at this layer.",
    highlight: true,
  },
  {
    title: "Execution",
    body: "Execution is where Virtual Employees, agents, and integrations act — always within approved capability envelopes, always recorded in the event ledger, always attributable to the human who authorized the scope.",
    highlight: false,
  },
  {
    title: "Constitutional Seal",
    body: "Constitutional governance is enforced through a cryptographic seal — the governance articles are hashed on every kernel boot, and the seal can only be regenerated by a split-key ceremony requiring multiple human stewards. No single operator, no administrator, no automated process can modify the constitutional layer unilaterally.",
    highlight: false,
  },
];

const landscape = [
  {
    label: "Automation platforms",
    body: "connect systems — they move data between services. They do not enforce authority boundaries, maintain audit-grade provenance, or provide a single kill switch when something goes wrong. When AI agents run inside them, no one controls the scope.",
  },
  {
    label: "Agent frameworks",
    body: "let AI call functions and produce outputs. Most lack hard authority boundaries, durable process identity, and the ability to trace any outcome to the human who approved it. When the agent drifts, no structural failsafe exists.",
  },
  {
    label: "Traditional CRMs",
    body: "track activity and pipeline. They do not provide immutable ledgers, full-funnel attribution, composite scoring with governed signals, or learning loops that improve under governance. History can be rewritten. The chain cannot be audited.",
  },
  {
    label: "Knowledge tools",
    body: "store documents and databases. They do not enforce decision modeling, version-control doctrine, connect knowledge to execution outcomes, or distinguish between human-verified facts and AI-generated suggestions. Information goes in. Intelligence does not come out.",
  },
  {
    label: "Observability dashboards",
    body: "show you what happened. They do not control what is allowed to happen next. They observe — they do not govern.",
  },
];

const criteria = [
  {
    label: "Operational complexity",
    desc: "— multiple domains, compliance requirements, or cross-functional workflows that exceed what automation platforms can govern",
  },
  {
    label: "Accountability requirements",
    desc: "— regulatory, fiduciary, or executive mandates that demand audit-grade provenance on AI actions",
  },
  {
    label: "Scale of AI ambition",
    desc: "— organizations ready to deploy AI as workforce, not as tooling",
  },
  {
    label: "Commitment to governance",
    desc: "— leadership that understands authority must be structural, not aspirational",
  },
];

export default function DominusOSPage() {
  return (
    <>
      <style
        dangerouslySetInnerHTML={{
          __html: `
            .dominus-os-dark {
              --dos-bg: #0a0a0b;
              --dos-bg-elevated: #111113;
              --dos-bg-surface: #18181b;
              --dos-text: #e8e6e1;
              --dos-text-secondary: #8a8880;
              --dos-text-muted: #5a5850;
              --dos-accent: #c4956a;
              --dos-accent-dim: #8a6a4a;
              --dos-border: #222220;
              --dos-border-light: #2a2a28;
              background: var(--dos-bg);
              color: var(--dos-text);
            }
            .dominus-os-dark .dos-noise {
              background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.03'/%3E%3C/svg%3E");
            }
            @keyframes dos-pulse {
              0%, 100% { opacity: 1; }
              50% { opacity: 0.4; }
            }
            .dos-status-dot {
              animation: dos-pulse 2s infinite;
            }
            .dos-divider {
              background: var(--dos-border);
            }
            .dos-divider::after {
              content: '';
              display: block;
              width: 60px;
              height: 1px;
              background: var(--dos-accent-dim);
            }
            .dos-card {
              background: var(--dos-bg-surface);
              border: 1px solid var(--dos-border-light);
              border-bottom: 2px solid var(--dos-accent-dim);
            }
            .dos-card-highlight {
              background: linear-gradient(140deg, var(--dos-bg-surface), #1c1b18);
              border-color: var(--dos-accent-dim);
            }
            .dos-cta-button {
              color: var(--dos-text);
              background: transparent;
              border: 1px solid var(--dos-accent-dim);
              transition: all 0.4s ease;
            }
            .dos-cta-button:hover {
              background: var(--dos-accent-dim);
              color: var(--dos-bg);
              border-color: var(--dos-accent);
            }
          `,
        }}
      />

      <div className="dominus-os-dark">
        <div
          className="dos-noise pointer-events-none fixed inset-0 z-[60]"
          aria-hidden="true"
        />

        {/* ─── HERO ─────────────────────────────────────────────── */}
        <section className="relative flex min-h-[100vh] flex-col justify-center pt-24 pb-32">
          <div
            className="absolute bottom-0 left-1/2 h-[120px] w-px -translate-x-1/2"
            style={{
              background:
                "linear-gradient(to bottom, transparent, var(--dos-accent-dim), transparent)",
            }}
            aria-hidden="true"
          />
          <div className="mx-auto w-full max-w-[860px] px-8">
            <p
              className="mb-10 text-[0.7rem] font-normal uppercase tracking-[0.25em]"
              style={{ color: "var(--dos-accent)" }}
            >
              The Human-Governed AI Hypervisor
            </p>
            <h1
              className="font-crimson text-[clamp(2.8rem,6vw,4.5rem)] font-light leading-[1.15]"
              style={{
                color: "var(--dos-text)",
                letterSpacing: "-0.02em",
              }}
            >
              Run AI as governed processes.
              <br />
              See everything. Stop&nbsp;everything.
            </h1>
            <p
              className="mt-8 max-w-[600px] text-[1.05rem] font-light leading-[1.8]"
              style={{ color: "var(--dos-text-secondary)" }}
            >
              DominusOS is a human-governed AI hypervisor &mdash; a control layer
              beneath AI execution where every action passes through a mandatory
              syscall gate, every capability is scoped and revocable, and every
              outcome traces to human authority. Built on a federated microkernel
              with event-sourced determinism, multi-kernel governance, a governed
              intelligence layer, cryptographically sealed constitutional
              authority, and tenant isolation. Not another AI product. An
              operating system with structural governance enforced by
              architecture.
            </p>
            <div className="mt-14 flex items-center gap-3">
              <div
                className="dos-status-dot h-1.5 w-1.5 rounded-full"
                style={{
                  background: "#4a9",
                  boxShadow: "0 0 8px rgba(68, 170, 136, 0.5)",
                }}
              />
              <span
                className="font-mono text-[0.7rem] uppercase tracking-[0.1em]"
                style={{ color: "var(--dos-text-muted)" }}
              >
                System live &middot; Production since 2025
              </span>
            </div>
          </div>
        </section>

        {/* ─── PREMISE ──────────────────────────────────────────── */}
        <section className="py-28 md:py-36">
          <div className="mx-auto max-w-[860px] px-8">
            <div className="dos-divider h-px w-full" />
            <div className="pt-16">
              <p
                className="font-crimson text-[clamp(1.4rem,3vw,1.8rem)] font-normal leading-[1.7]"
                style={{ color: "var(--dos-text-secondary)" }}
              >
                The AI industry is scaling capability faster than it is scaling
                control. Every new agent framework, every new integration, every
                new autonomous process{" "}
                <em
                  className="not-italic"
                  style={{ color: "var(--dos-text)" }}
                >
                  widens the gap between what AI can do and what organizations
                  can govern.
                </em>
              </p>
              <p
                className="mt-8 font-crimson text-[clamp(1.4rem,3vw,1.8rem)] font-normal leading-[1.7]"
                style={{ color: "var(--dos-text-secondary)" }}
              >
                DominusOS closes that gap &mdash; not with policy, but with
                architecture. A mandatory control layer beneath every AI action.{" "}
                <em
                  className="not-italic"
                  style={{ color: "var(--dos-text)" }}
                >
                  Nothing executes without bounded, revocable, human-granted
                  authority.
                </em>
              </p>
            </div>
          </div>
        </section>

        {/* ─── THREE STRUCTURAL GUARANTEES ─────────────────────── */}
        <section className="py-20 md:py-28">
          <div className="mx-auto max-w-[860px] px-8">
            <p
              className="mb-16 text-[0.7rem] uppercase tracking-[0.25em]"
              style={{ color: "var(--dos-accent)" }}
            >
              Three Structural Guarantees
            </p>
            <div className="grid grid-cols-1 gap-5 md:grid-cols-3">
              {guarantees.map((g) => (
                <div
                  key={g.title}
                  className="dos-card rounded-2xl p-6"
                >
                  <h3
                    className="mb-3 font-crimson text-xl font-semibold"
                    style={{ color: "var(--dos-text)" }}
                  >
                    {g.title}
                  </h3>
                  <p
                    className="text-[0.9rem] leading-[1.75]"
                    style={{ color: "var(--dos-text-secondary)" }}
                  >
                    {g.body}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ─── THE PROBLEM ────────────────────────────────────── */}
        <section
          className="py-20 md:py-28"
          style={{ borderTop: "1px solid var(--dos-border)" }}
        >
          <div className="mx-auto max-w-[860px] px-8">
            <div className="grid gap-10 md:grid-cols-[1fr_1.1fr]">
              <div>
                <p
                  className="mb-3 text-[0.7rem] uppercase tracking-[0.25em]"
                  style={{ color: "var(--dos-accent)" }}
                >
                  The Problem
                </p>
                <h2
                  className="font-crimson text-[clamp(1.8rem,3.5vw,2.4rem)] font-light leading-[1.25]"
                  style={{ color: "var(--dos-text)" }}
                >
                  Systems that act without governance erode trust. Systems that
                  cannot learn erode value.
                </h2>
              </div>
              <div>
                <p
                  className="mb-5 text-[0.95rem] leading-[1.8]"
                  style={{ color: "var(--dos-text-secondary)" }}
                >
                  Most AI tools force a choice between power and accountability.
                  Either systems act too freely &mdash; creating legal, ethical,
                  and operational risk &mdash; or they are locked down so tightly
                  they cannot adapt to real work. As organizations scale AI, the
                  cost of this gap is carried by operators and executives who
                  must still answer for outcomes they did not directly control.
                </p>
                <p
                  className="text-[0.95rem] leading-[1.8]"
                  style={{ color: "var(--dos-text-secondary)" }}
                >
                  Most stacks can automate tasks. Almost none can prove what
                  happened end-to-end, tie actions to outcomes, and keep
                  authority intact while organizational intelligence compounds.
                  Monitoring tells you what happened. Only a hypervisor layer
                  &mdash; beneath execution, not above it &mdash; can determine
                  what is permitted to happen.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* ─── THE ARCHITECTURE ────────────────────────────────── */}
        <section
          className="py-20 md:py-28"
          style={{
            background: "var(--dos-bg-elevated)",
            borderTop: "1px solid var(--dos-border)",
            borderBottom: "1px solid var(--dos-border)",
          }}
        >
          <div className="mx-auto max-w-[860px] px-8">
            <p
              className="mb-4 text-[0.7rem] uppercase tracking-[0.25em]"
              style={{ color: "var(--dos-accent)" }}
            >
              The Architecture
            </p>
            <h2
              className="mb-10 font-crimson text-[clamp(1.8rem,3.5vw,2.4rem)] font-light leading-[1.25]"
              style={{ color: "var(--dos-text)" }}
            >
              Not an agent. Not a chatbot. A&nbsp;hypervisor.
            </h2>
            <div className="space-y-6">
              <p
                className="text-[0.95rem] leading-[1.8]"
                style={{ color: "var(--dos-text-secondary)" }}
              >
                DominusOS is a governed computing substrate built on a federated
                microkernel architecture. At its core, a mandatory syscall gate
                mediates all execution &mdash; no process writes, communicates,
                deploys, or commits resources without passing through this
                governance checkpoint. Capability-based authority ensures every
                process operates within an explicit envelope: scoped,
                time-bound, and granted by a named human steward. Event-sourced
                determinism captures every state change as an immutable,
                sequenced event, enabling full replay and audit of any execution
                path.
              </p>
              <p
                className="text-[0.95rem] leading-[1.8]"
                style={{ color: "var(--dos-text-secondary)" }}
              >
                The architecture extends to a federated multi-kernel model. Each
                organizational domain operates its own kernel with its own
                isolated data store, audit chain, and governance rules &mdash;
                while remaining governed by a sovereign layer that holds
                constitutional authority. A federated knowledge graph aggregates
                abstracted cross-domain intelligence without exposing raw domain
                data. A behavioral shift detected in one domain surfaces as a
                relevant signal in another. The intelligence is combinatorial:
                each new domain multiplies the intelligence available to every
                domain already connected.
              </p>
              <p
                className="text-[0.95rem] leading-[1.8]"
                style={{ color: "var(--dos-text-secondary)" }}
              >
                A governed intelligence layer detects patterns, proposes actions
                with stated evidence, and evolves under explicit operator
                authority. An autonomic planner follows a tiered authority model
                &mdash; from auto-proposed optimizations to governance-gated
                changes affecting constitutional rules. A counsel layer produces
                evidence-cited operational briefs. Deep temporal memory enables
                natural language queries against the full depth of operational
                history. Intelligence compounds because nothing is discarded and
                everything is connected.
              </p>
              <p
                className="text-[0.95rem] leading-[1.8]"
                style={{ color: "var(--dos-text-secondary)" }}
              >
                Constitutional governance is cryptographically enforced. The
                kernel&apos;s invariant foundation is verified on every boot. The
                governance canon is cryptographically hashed and sealed &mdash;
                if any file is modified, the kernel halts. The seal can only be
                regenerated through a split-key ceremony requiring the physical
                consent of multiple designated human stewards.
              </p>
              <p
                className="text-[0.95rem] leading-[1.8]"
                style={{ color: "var(--dos-text-secondary)" }}
              >
                The operator surface is a native desktop application with live
                process visibility, tab-based task management, and direct kill
                authority. A companion mobile app extends operator reach. The
                structured knowledge layer includes an assembly surface &mdash;
                a block-based editing environment where decisions are modeled
                with rationale, projects carry lifecycle stages, and doctrine is
                weighted and version-controlled.
              </p>
              <p
                className="font-crimson text-lg italic"
                style={{ color: "var(--dos-text-muted)" }}
              >
                One kernel federation. Multiple governed surfaces. One knowledge
                graph. One constitutional canon.
              </p>
            </div>
          </div>
        </section>

        {/* ─── CONTROL PLANE ──────────────────────────────────── */}
        <section className="py-20 md:py-28">
          <div className="mx-auto max-w-[860px] px-8">
            <div className="grid gap-10 md:grid-cols-[1fr_1.1fr]">
              <div>
                <p
                  className="mb-3 text-[0.7rem] uppercase tracking-[0.25em]"
                  style={{ color: "var(--dos-accent)" }}
                >
                  Control Plane
                </p>
                <h2
                  className="font-crimson text-[clamp(1.8rem,3.5vw,2.4rem)] font-light leading-[1.25]"
                  style={{ color: "var(--dos-text)" }}
                >
                  A single surface for every AI process in your organization.
                </h2>
              </div>
              <div>
                <p
                  className="mb-5 text-[0.95rem] leading-[1.8]"
                  style={{ color: "var(--dos-text-secondary)" }}
                >
                  DominusOS gives the operator one surface to see what&apos;s
                  running, what&apos;s queued, what changed, and what every
                  process touched. Live status, run history, data provenance, and
                  authority boundaries &mdash; all in one view. Not scattered
                  across vendor dashboards. One control plane, one truth.
                </p>
                <p
                  className="text-[0.95rem] leading-[1.8]"
                  style={{ color: "var(--dos-text-secondary)" }}
                >
                  Every process registers or it does not run. Scheduled jobs
                  execute autonomously under governance. Every write operation
                  passes through the syscall gate &mdash; the mandatory
                  governance checkpoint where the human governs and the system
                  executes. The boundary is structural, not behavioral.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* ─── KILL SWITCH ────────────────────────────────────── */}
        <section
          className="py-20 md:py-28"
          style={{
            background: "var(--dos-bg-elevated)",
            borderTop: "1px solid var(--dos-border)",
            borderBottom: "1px solid var(--dos-border)",
          }}
        >
          <div className="mx-auto max-w-[860px] px-8">
            <div className="grid gap-10 md:grid-cols-[1fr_1.1fr]">
              <div>
                <p
                  className="mb-3 text-[0.7rem] uppercase tracking-[0.25em]"
                  style={{ color: "var(--dos-accent)" }}
                >
                  Kill Switch
                </p>
                <h2
                  className="font-crimson text-[clamp(1.8rem,3.5vw,2.4rem)] font-light leading-[1.25]"
                  style={{ color: "var(--dos-text)" }}
                >
                  One action halts every AI process. Instantly. Visibly.
                </h2>
              </div>
              <div>
                <p
                  className="mb-5 text-[0.95rem] leading-[1.8]"
                  style={{ color: "var(--dos-text-secondary)" }}
                >
                  DominusOS enforces a system-level halt that stops all
                  AI-driven execution across every subsystem. No silent
                  continuation. No orphaned processes. Revocation cascades ensure
                  that when authority is withdrawn, all derived capabilities are
                  transitively and immediately revoked. The system fails safe
                  &mdash; and the operator sees it happen in real time, with a
                  full audit trail of what was stopped and why.
                </p>
                <p
                  className="text-[0.95rem] leading-[1.8]"
                  style={{ color: "var(--dos-text-secondary)" }}
                >
                  This is the guarantee that makes everything else trustworthy.
                  If you cannot stop it, you do not govern it. DominusOS makes
                  halt authority a first-class structural capability &mdash; not
                  a panic button buried in settings, but an architectural
                  guarantee the operator holds at all times.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* ─── AUTHORITY STRUCTURE ────────────────────────────── */}
        <section className="py-20 md:py-28">
          <div className="mx-auto max-w-[860px] px-8">
            <div className="mb-12 text-center">
              <p
                className="mb-3 text-[0.7rem] uppercase tracking-[0.25em]"
                style={{ color: "var(--dos-accent)" }}
              >
                Authority Structure
              </p>
              <h2
                className="mx-auto max-w-[500px] font-crimson text-[clamp(1.8rem,3.5vw,2.4rem)] font-light leading-[1.25]"
                style={{ color: "var(--dos-text)" }}
              >
                A simple structure that scales.
              </h2>
            </div>
            <div className="grid grid-cols-1 gap-5 sm:grid-cols-2">
              {authorityLayers.map((layer) => (
                <div
                  key={layer.title}
                  className={`rounded-2xl p-6 ${layer.highlight ? "dos-card-highlight" : "dos-card"}`}
                >
                  <h3
                    className="mb-3 font-crimson text-lg font-semibold"
                    style={{ color: "var(--dos-text)" }}
                  >
                    {layer.title}
                  </h3>
                  <p
                    className="text-[0.88rem] leading-[1.75]"
                    style={{ color: "var(--dos-text-secondary)" }}
                  >
                    {layer.body}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ─── THESIS QUOTE ───────────────────────────────────── */}
        <section className="py-28 md:py-36 text-center">
          <div className="mx-auto max-w-[860px] px-8">
            <blockquote
              className="mx-auto max-w-[640px] font-crimson text-[clamp(1.5rem,3.5vw,2rem)] font-light italic leading-relaxed"
              style={{ color: "var(--dos-text)" }}
            >
              &ldquo;Monitoring records what happened.
              <br />A hypervisor determines what is
              <br />
              permitted to happen.&rdquo;
            </blockquote>
            <cite
              className="mt-8 block font-mono text-[0.65rem] not-italic uppercase tracking-[0.2em]"
              style={{ color: "var(--dos-text-muted)" }}
            >
              DominusOS White Paper, &sect;2
            </cite>
          </div>
        </section>

        {/* ─── WHO IT'S FOR ───────────────────────────────────── */}
        <section
          className="py-20 md:py-28"
          style={{ borderTop: "1px solid var(--dos-border)" }}
        >
          <div className="mx-auto max-w-[860px] px-8 text-center">
            <p
              className="mb-3 text-[0.7rem] uppercase tracking-[0.25em]"
              style={{ color: "var(--dos-accent)" }}
            >
              Who It&apos;s For
            </p>
            <h2
              className="mx-auto mb-6 max-w-[600px] font-crimson text-[clamp(1.8rem,3.5vw,2.4rem)] font-light leading-[1.25]"
              style={{ color: "var(--dos-text)" }}
            >
              Built for people who must account for every decision.
            </h2>
            <p
              className="mx-auto max-w-[640px] text-[0.95rem] leading-[1.8]"
              style={{ color: "var(--dos-text-secondary)" }}
            >
              DominusOS is built for operators, founders, and executives who
              cannot afford black boxes &mdash; and cannot afford to slow down to
              avoid them. It assumes that someone must always be able to explain
              what happened, why it happened, and who was responsible, regardless
              of which domain the action occurred in. Governance is not bolted on
              after the fact; it is enforced at the architectural level where
              execution occurs.
            </p>
          </div>
        </section>

        {/* ─── SOVEREIGNTY ────────────────────────────────────── */}
        <section
          className="py-20 md:py-28"
          style={{
            background: "var(--dos-bg-elevated)",
            borderTop: "1px solid var(--dos-border)",
            borderBottom: "1px solid var(--dos-border)",
          }}
        >
          <div className="mx-auto max-w-[860px] px-8">
            <div className="grid gap-10 md:grid-cols-[1fr_1.1fr]">
              <div>
                <p
                  className="mb-3 text-[0.7rem] uppercase tracking-[0.25em]"
                  style={{ color: "var(--dos-accent)" }}
                >
                  The Foundation
                </p>
                <h2
                  className="font-crimson text-[clamp(1.8rem,3.5vw,2.4rem)] font-light leading-[1.25]"
                  style={{ color: "var(--dos-text)" }}
                >
                  Built for sovereignty, not surveillance.
                </h2>
              </div>
              <div>
                <p
                  className="mb-5 text-[0.95rem] leading-[1.8]"
                  style={{ color: "var(--dos-text-secondary)" }}
                >
                  Most AI systems are designed to learn from you in ways that
                  serve their creators. DominusOS inverts this. Tenant isolation
                  and capability-based authority make unauthorized data
                  extraction structurally difficult by design &mdash; not because
                  of a promise, but because the architecture constrains it. Your
                  data, your processes, your intelligence. Sovereign by design.
                </p>
                <p
                  className="text-[0.95rem] leading-[1.8]"
                  style={{ color: "var(--dos-text-secondary)" }}
                >
                  For people who must protect discretion, confidentiality, and
                  fiduciary duty, this is not a feature. It is the reason to
                  choose DominusOS.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* ─── IN PRODUCTION ──────────────────────────────────── */}
        <section className="py-20 md:py-28">
          <div className="mx-auto max-w-[860px] px-8">
            <div className="grid gap-10 md:grid-cols-[1fr_1.1fr]">
              <div>
                <p
                  className="mb-3 text-[0.7rem] uppercase tracking-[0.25em]"
                  style={{ color: "var(--dos-accent)" }}
                >
                  In Production
                </p>
                <h2
                  className="font-crimson text-[clamp(1.8rem,3.5vw,2.4rem)] font-light leading-[1.25]"
                  style={{ color: "var(--dos-text)" }}
                >
                  Running live. Not a&nbsp;whitepaper.
                </h2>
              </div>
              <div>
                <p
                  className="mb-5 text-[0.95rem] leading-[1.8]"
                  style={{ color: "var(--dos-text-secondary)" }}
                >
                  DominusOS is not a proposal or a prototype. It is running in
                  production &mdash; orchestrating governed AI operations across
                  federated domain kernels with full tenant isolation,
                  independent audit chains, and sovereign-inherited
                  constitutional governance. Multiple virtual employees execute
                  daily tasks with real tools across production-scale operations.
                  A structured knowledge layer unifies organizational memory
                  across every domain &mdash; decisions, projects, doctrine, and
                  operational knowledge stored as versioned nodes in a connected
                  graph.
                </p>
                <p
                  className="mb-5 text-[0.95rem] leading-[1.8]"
                  style={{ color: "var(--dos-text-secondary)" }}
                >
                  Governed business workflows track engagement, enforce follow-up
                  discipline, and detect stale data automatically. Autonomous
                  scheduled operations run under governance with full
                  attribution. A governed intelligence layer detects patterns,
                  proposes actions with evidence, and evolves within explicit
                  authority bounds. A counsel layer produces evidence-cited
                  operational briefs from the system to the operator. The
                  constitutional canon is cryptographically sealed with split-key
                  authority. The kill switch halts all AI execution instantly and
                  visibly.
                </p>
                <p
                  className="text-[0.95rem] leading-[1.8]"
                  style={{ color: "var(--dos-text-secondary)" }}
                >
                  The hypervisor architecture is a deployable pattern. Any
                  multi-domain operation that needs accountability, structured
                  cognition, cross-domain intelligence, and AI governance can run
                  a version of this. The architecture is designed for extension to
                  IoT and autonomous edge environments. AI governance today.
                  Autonomous infrastructure tomorrow. The pattern scales. The
                  philosophy does not compromise.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* ─── COMPETITIVE LANDSCAPE ──────────────────────────── */}
        <section
          className="py-20 md:py-28"
          style={{
            background: "var(--dos-bg-elevated)",
            borderTop: "1px solid var(--dos-border)",
            borderBottom: "1px solid var(--dos-border)",
          }}
        >
          <div className="mx-auto max-w-[860px] px-8">
            <p
              className="mb-3 text-[0.7rem] uppercase tracking-[0.25em]"
              style={{ color: "var(--dos-accent)" }}
            >
              Competitive Landscape
            </p>
            <h2
              className="mb-10 font-crimson text-[clamp(1.8rem,3.5vw,2.4rem)] font-light leading-[1.25]"
              style={{ color: "var(--dos-text)" }}
            >
              Where DominusOS sits &mdash; and what it replaces.
            </h2>
            <p
              className="mb-8 text-[0.95rem] leading-[1.8]"
              style={{ color: "var(--dos-text-secondary)" }}
            >
              Most organizations assemble a patchwork of tools that each solve
              one problem. None of them solve the governance problem.
            </p>
            <div className="space-y-5">
              {landscape.map((item) => (
                <p
                  key={item.label}
                  className="text-[0.95rem] leading-[1.8]"
                  style={{
                    color: "var(--dos-text-secondary)",
                    borderBottom: "1px solid var(--dos-border)",
                    paddingBottom: "20px",
                  }}
                >
                  <strong style={{ color: "var(--dos-text)" }}>
                    {item.label}
                  </strong>{" "}
                  {item.body}
                </p>
              ))}
              <p
                className="text-[0.95rem] leading-[1.8]"
                style={{ color: "var(--dos-text-secondary)" }}
              >
                <strong style={{ color: "var(--dos-accent)" }}>
                  DominusOS
                </strong>{" "}
                operates at the hypervisor layer &mdash; beneath execution,
                above infrastructure. A mandatory syscall gate, capability-based
                authority, event-sourced determinism, federated multi-kernel
                governance, governed intelligence, and structural kill authority.
                Execute, govern, prove, halt &mdash; in one system. Not bolted
                on. Architected in.
              </p>
            </div>
          </div>
        </section>

        {/* ─── ACCESS ─────────────────────────────────────────── */}
        <section className="py-28 md:py-32">
          <div className="mx-auto max-w-[860px] px-8">
            <p
              className="mb-10 text-[0.7rem] uppercase tracking-[0.25em]"
              style={{ color: "var(--dos-accent)" }}
            >
              Founding Deployments
            </p>
            <h2
              className="mb-8 max-w-[580px] font-crimson text-[clamp(1.8rem,4vw,2.5rem)] font-light leading-[1.3]"
              style={{ color: "var(--dos-text)" }}
            >
              Shape how AI governance gets&nbsp;built.
            </h2>
            <p
              className="mb-6 max-w-[520px] text-[0.95rem] leading-[1.8]"
              style={{ color: "var(--dos-text-secondary)" }}
            >
              We deploy governed intelligence into a limited number of
              organizations per year &mdash; not to pilot governance, but to
              prove the pattern at scale. Founding partners receive hands-on
              deployment, direct architectural input, and favorable terms.
            </p>

            <div
              className="mt-12 rounded-xl p-10"
              style={{
                background: "var(--dos-bg-surface)",
                border: "1px solid var(--dos-border-light)",
                borderLeft: "2px solid var(--dos-accent-dim)",
              }}
            >
              <h4
                className="mb-6 font-mono text-[0.65rem] uppercase tracking-[0.2em]"
                style={{ color: "var(--dos-text-muted)" }}
              >
                We evaluate fit on
              </h4>
              {criteria.map((item, i) => (
                <div
                  key={item.label}
                  className="py-2.5 text-[0.88rem] leading-[1.7]"
                  style={{
                    color: "var(--dos-text-secondary)",
                    borderBottom:
                      i < criteria.length - 1
                        ? "1px solid var(--dos-border)"
                        : "none",
                  }}
                >
                  <span style={{ color: "var(--dos-text)", fontWeight: 400 }}>
                    {item.label}
                  </span>{" "}
                  {item.desc}
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ─── CTA ────────────────────────────────────────────── */}
        <section className="py-20 md:py-32">
          <div className="mx-auto max-w-[860px] px-8">
            <a
              href="mailto:mark@dominusfoundry.com?subject=DominusOS%20Inquiry"
              className="dos-cta-button inline-block rounded-lg px-10 py-4 font-mono text-[0.7rem] uppercase tracking-[0.2em]"
            >
              Request a Conversation
            </a>
            <p
              className="mt-6 text-xs italic"
              style={{ color: "var(--dos-text-muted)" }}
            >
              We respond to qualified inquiries within 48 hours.
            </p>
          </div>
        </section>

        {/* ─── DEEP LINKS ─────────────────────────────────────── */}
        <section
          className="py-12"
          style={{ borderTop: "1px solid var(--dos-border)" }}
        >
          <div className="mx-auto max-w-[860px] px-8 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div
              className="font-crimson text-sm"
              style={{ color: "var(--dos-text-muted)" }}
            >
              DominusOS advances the Human-Governed Intelligence standard.
            </div>
            <div
              className="flex flex-wrap items-center gap-4 font-mono text-[0.65rem] tracking-[0.1em]"
              style={{ color: "var(--dos-text-muted)" }}
            >
              <a
                href="https://dominusos.ai/whitepaper"
                className="transition-colors duration-300"
                style={{ color: "var(--dos-text-secondary)" }}
                target="_blank"
                rel="noopener noreferrer"
              >
                White Paper
              </a>
              <span>&middot;</span>
              <a
                href="https://dominusos.ai"
                className="transition-colors duration-300"
                style={{ color: "var(--dos-text-secondary)" }}
                target="_blank"
                rel="noopener noreferrer"
              >
                dominusos.ai
              </a>
              <span>&middot;</span>
              <Link
                href="/systems"
                className="transition-colors duration-300"
                style={{ color: "var(--dos-text-secondary)" }}
              >
                Systems We Build
              </Link>
            </div>
          </div>
        </section>
      </div>
    </>
  );
}
